name: Publish

on:
  push:
    tags:
      - '*@*.*.*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish Job
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - name: Install deps
        run: npm ci

      - name: Print environment info
        run: npx nx report

      - name: Publish packages
        run: |
          npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
