name: Release

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  release:
    name: Release Job
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Set git credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup node
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Test libs
        run: npx nx run-many -t test --projects=tag:lib --no-cloud  --verbose

      - name: Build libs
        run: npx nx run-many -t build --projects=tag:lib --no-cloud --verbose

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      
      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}


        # Version is calculated from git history based on conentional commits https://www.conventionalcommits.org/en/v1.0.0/#summary 


      - name: Fetch main remote branch
        if: github.ref == 'refs/heads/development'
        run: git fetch origin main:refs/remotes/origin/main

      - name: Create Prerelease
        if: github.ref == 'refs/heads/development'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx release --skip-publish --specifier prerelease --preid beta-${{ env.COMMIT_SHORT_SHA }}

        # OR if on main branch

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx release --skip-publish
